import { useEffect, useMemo, useState } from "react";
import * as api from "./api";
import { AlertIcon, BoxesIcon, CheckIcon, DownloadIcon, EyeIcon, LockIcon, MoreIcon, PencilIcon, PlayIcon, PlusIcon, RefreshIcon, SearchIcon, ServerIcon, SettingsIcon, TrashIcon, WalletIcon, XIcon } from "./icons";
import type { BalanceInfo, ModelStatus, Provider, ProviderInput, ProviderType, Snapshot, StorageInfo } from "./types";
import { AccountsPage, KeysPage, UsagePage } from "./ManagementPages";
import { ProfilesPage } from "./ProfilesPage";
import "./App.css";

type Page = "providers" | "profiles" | "accounts" | "keys" | "usage" | "models" | "settings";
const typeLabels: Record<ProviderType, string> = { "new-api": "New API", sub2api: "Sub2API", "openai-compatible": "OpenAI Compatible" };
const apiLabels = { responses: "Responses", "chat-completions": "Chat Completions", unknown: "未识别" } as const;
const emptySnapshot: Snapshot = { providers: [], models: [], balances: [], profiles: [] };

function formatTime(value?: string) {
  if (!value) return "尚未检测";
  const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(date);
}
function money(value?: number) { return value == null ? "--" : new Intl.NumberFormat("zh-CN", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value); }
function messageOf(error: unknown) { return error instanceof Error ? error.message : String(error); }

function Modal({ provider, onClose, onSaved }: { provider?: Provider; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState<ProviderInput>({ id: provider?.id, name: provider?.name ?? "", type: provider?.type ?? "openai-compatible", baseUrl: provider?.baseUrl ?? "", apiKey: "", accountToken: "", refreshToken: "", tokenExpiresAt: provider?.tokenExpiresAt, accountUserId: provider?.accountUserId ?? "", enabled: provider?.enabled ?? true });
  const [showKey, setShowKey] = useState(false); const [showAccountToken, setShowAccountToken] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { await api.saveProvider({ ...form, apiKey: form.apiKey || undefined, accountToken: form.accountToken || undefined, refreshToken: form.refreshToken || undefined, accountUserId: form.type === "new-api" ? form.accountUserId : undefined }); onSaved(); } catch (value) { setError(messageOf(value)); } finally { setSaving(false); } }
  return <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><form className="modal" onSubmit={submit}>
    <header className="modal-header"><div><h2>{provider ? "编辑服务商" : "添加服务商"}</h2><p>连接信息仅保存在本机。</p></div><button type="button" className="icon-button" onClick={onClose} aria-label="关闭"><XIcon /></button></header>
    <div className="form-grid"><label><span>服务商名称</span><input autoFocus required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="例如：Team New API" /></label>
      <label><span>服务商类型</span><select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as ProviderType })}><option value="new-api">New API</option><option value="sub2api">Sub2API</option><option value="openai-compatible">OpenAI Compatible</option></select></label>
      <label className="span-2"><span>Base URL</span><input required type="url" value={form.baseUrl} onChange={(e) => setForm({ ...form, baseUrl: e.target.value })} placeholder="https://api.example.com" /><small>可填写站点根地址或以 /v1 结尾的地址。</small></label>
      <label className="span-2"><span>模型 API Key {provider?.hasApiKey && <em>已安全保存</em>}</span><div className="input-action"><input required={!provider?.hasApiKey} type={showKey ? "text" : "password"} value={form.apiKey} onChange={(e) => setForm({ ...form, apiKey: e.target.value })} placeholder={provider?.hasApiKey ? "留空则不修改" : "sk-..."}/><button type="button" onClick={() => setShowKey(!showKey)} aria-label="显示或隐藏模型 API Key"><EyeIcon /></button></div><small>仅用于模型列表和实际请求测试。</small></label>
      {form.type !== "openai-compatible" && <><label className={form.type === "sub2api" ? "span-2" : ""}><span>账户访问令牌 {provider?.hasAccountToken && <em>已安全保存</em>}</span><div className="input-action"><input required={!provider?.hasAccountToken} type={showAccountToken ? "text" : "password"} value={form.accountToken} onChange={(e) => setForm({ ...form, accountToken: e.target.value })} placeholder={provider?.hasAccountToken ? "留空则不修改" : form.type === "new-api" ? "New API 系统访问令牌" : "Sub2API 控制台 JWT"}/><button type="button" onClick={() => setShowAccountToken(!showAccountToken)} aria-label="显示或隐藏账户访问令牌"><EyeIcon /></button></div><small>{form.type === "sub2api" ? "登录后签发的 JWT，过期后需要更新。" : "个人设置中生成的系统访问令牌。"}</small></label>{form.type === "sub2api" && <label className="span-2"><span>Refresh Token {provider?.hasRefreshToken && <em>已安全保存</em>}</span><input type="password" value={form.refreshToken} onChange={(e) => setForm({ ...form, refreshToken: e.target.value })} placeholder={provider?.hasRefreshToken ? "留空则不修改" : "可选，用于自动刷新过期 JWT"}/><small>建议与 Access Token 一起从登录会话中获取。</small></label>}{form.type === "new-api" && <label><span>New API 用户 ID</span><input required value={form.accountUserId} onChange={(e) => setForm({ ...form, accountUserId: e.target.value })} inputMode="numeric" placeholder="例如：42"/><small>账户菜单中显示的数字用户 ID。</small></label>}</>}
    </div>{error && <div className="inline-error"><AlertIcon />{error}</div>}
    <footer className="modal-footer"><label className="switch-label"><button type="button" role="switch" aria-checked={form.enabled} className={`switch ${form.enabled ? "on" : ""}`} onClick={() => setForm({ ...form, enabled: !form.enabled })}><span /></button>保存后启用</label><div><button type="button" className="button secondary" onClick={onClose}>取消</button><button className="button primary" disabled={saving}>{saving ? "保存中…" : "保存服务商"}</button></div></footer>
  </form></div>;
}

function ProvidersPage({ snapshot, reload }: { snapshot: Snapshot; reload: () => Promise<void> }) {
  const [editing, setEditing] = useState<Provider | "new" | null>(null); const [busy, setBusy] = useState<Record<string, string>>({}); const [openMenu, setOpenMenu] = useState<string | null>(null); const [notice, setNotice] = useState("");
  const balanceByProvider = useMemo(() => Object.fromEntries(snapshot.balances.map((item) => [item.providerId, item])), [snapshot.balances]);
  async function run(id: string, action: string, task: () => Promise<unknown>) { setBusy((v) => ({ ...v, [id]: action })); setNotice(""); try { await task(); await reload(); } catch (e) { setNotice(messageOf(e)); } finally { setBusy((v) => { const next = { ...v }; delete next[id]; return next; }); } }
  async function remove(provider: Provider) { setOpenMenu(null); if (!confirm(`删除“${provider.name}”及其检测记录？此操作无法撤销。`)) return; await run(provider.id, "删除中", () => api.deleteProvider(provider.id)); }
  return <section className="page"><div className="page-heading"><div><p className="eyebrow">连接中心</p><h1>服务商</h1><p>集中管理模型服务的连接、余额与运行状态。</p></div><button className="button primary" onClick={() => setEditing("new")}><PlusIcon />添加服务商</button></div>
    <div className="stats-strip"><div><span>服务商</span><strong>{snapshot.providers.length}</strong></div><div><span>已启用</span><strong>{snapshot.providers.filter((p) => p.enabled).length}</strong></div><div><span>已发现模型</span><strong>{snapshot.models.length}</strong></div><div><span>可用模型</span><strong>{snapshot.models.filter((m) => m.available && m.api !== "unknown").length}</strong></div></div>
    {notice && <div className="notice error"><AlertIcon />{notice}<button onClick={() => setNotice("")}><XIcon /></button></div>}
    {snapshot.providers.length === 0 ? <div className="empty"><div className="empty-icon"><ServerIcon /></div><h2>还没有服务商</h2><p>添加第一个 OpenAI 兼容服务，开始检测模型。</p><button className="button primary" onClick={() => setEditing("new")}><PlusIcon />添加服务商</button></div> : <div className="provider-list">
      {snapshot.providers.map((provider) => { const models = snapshot.models.filter((m) => m.providerId === provider.id); const balance = balanceByProvider[provider.id] as BalanceInfo | undefined; return <article className={`provider-row ${!provider.enabled ? "disabled" : ""}`} key={provider.id}>
        <div className="provider-main"><div className={`provider-mark type-${provider.type}`}>{provider.name.slice(0, 1).toUpperCase()}</div><div className="provider-copy"><div className="provider-title"><h2>{provider.name}</h2><span className={`status ${provider.enabled ? "online" : "off"}`}>{provider.enabled ? "已启用" : "已停用"}</span><span className="type-tag">{typeLabels[provider.type]}</span></div><p>{provider.baseUrl}</p><div className="provider-meta"><span><BoxesIcon />{models.length} 个模型</span><span><LockIcon />{provider.hasApiKey ? "模型密钥已保存" : "缺少模型密钥"}</span>{provider.type !== "openai-compatible" && <span><LockIcon />{provider.hasAccountToken ? "账户令牌已保存" : "缺少账户令牌"}</span>}<span>更新于 {formatTime(provider.updatedAt)}</span></div></div></div>
        <div className="provider-balance">{balance ? balance.supported ? <><span>{balance.accountName ? `${balance.accountName} · ` : ""}{provider.type === "new-api" ? "剩余额度" : "可用余额"}</span><strong>{provider.type === "new-api" ? `$ ${money(balance.quota)}` : `$ ${money(balance.balance)}`}</strong><small>{balance.subscriptionName ? `${balance.subscriptionName}${balance.subscriptionStatus ? ` · ${balance.subscriptionStatus}` : ""}` : balance.group ? `${balance.group}${balance.multiplier != null ? ` · ${balance.multiplier}×` : ""}` : balance.frozenBalance ? `冻结 $ ${money(balance.frozenBalance)}` : `查询于 ${formatTime(balance.checkedAt)}`}</small></> : <><span>账户信息</span><strong className="muted">查询失败</strong><small title={balance.error}>{balance.error}</small></> : <><span>账户信息</span><strong className="muted">尚未查询</strong><small>{provider.type === "openai-compatible" ? "兼容站可能不支持" : "需配置账户访问令牌"}</small></>}</div>
        <div className="provider-actions"><button className="button secondary compact" disabled={!!busy[provider.id] || !provider.enabled} onClick={() => run(provider.id, "获取模型中", () => api.fetchModels(provider.id))}><RefreshIcon />{busy[provider.id] === "获取模型中" ? "检测中…" : "检测模型"}</button><button className="icon-button bordered" disabled={!!busy[provider.id] || !provider.enabled} onClick={() => run(provider.id, "查询余额中", () => api.queryBalance(provider.id))} title="查询余额"><WalletIcon /></button><div className="menu-wrap"><button className="icon-button bordered" onClick={() => setOpenMenu(openMenu === provider.id ? null : provider.id)} aria-label="更多操作"><MoreIcon /></button>{openMenu === provider.id && <div className="menu"><button onClick={() => { setEditing(provider); setOpenMenu(null); }}><PencilIcon />编辑</button><button onClick={() => run(provider.id, "切换状态中", () => api.toggleProvider(provider.id, !provider.enabled))}>{provider.enabled ? <XIcon /> : <CheckIcon />}{provider.enabled ? "停用" : "启用"}</button><button className="danger" onClick={() => remove(provider)}><TrashIcon />删除</button></div>}</div></div>
      </article>; })}
    </div>}
    {editing && <Modal provider={editing === "new" ? undefined : editing} onClose={() => setEditing(null)} onSaved={async () => { setEditing(null); await reload(); }} />}
  </section>;
}

function ModelsPage({ snapshot, reload }: { snapshot: Snapshot; reload: () => Promise<void> }) {
  const [providerFilter, setProviderFilter] = useState("all"); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<Set<string>>(new Set()); const [testing, setTesting] = useState<Set<string>>(new Set()); const [notice, setNotice] = useState("");
  const keyOf = (m: ModelStatus) => `${m.providerId}::${m.modelId}`;
  const filtered = snapshot.models.filter((m) => (providerFilter === "all" || m.providerId === providerFilter) && `${m.modelId} ${m.name} ${m.providerName}`.toLowerCase().includes(query.toLowerCase()));
  async function test(items: ModelStatus[]) { setNotice(""); const keys = new Set(items.map(keyOf)); setTesting((old) => new Set([...old, ...keys])); const errors: string[] = []; for (const model of items) { try { await api.testModel(model.providerId, model.modelId); } catch (e) { errors.push(`${model.modelId}: ${messageOf(e)}`); } finally { setTesting((old) => { const next = new Set(old); next.delete(keyOf(model)); return next; }); } } await reload(); if (errors.length) setNotice(errors.join("；")); }
  const allSelected = filtered.length > 0 && filtered.every((m) => selected.has(keyOf(m)));
  return <section className="page"><div className="page-heading"><div><p className="eyebrow">模型目录</p><h1>模型</h1><p>发现、筛选并验证所有服务商的模型端点。</p></div><button className="button primary" disabled={!selected.size || testing.size > 0} onClick={() => test(snapshot.models.filter((m) => selected.has(keyOf(m))))}><PlayIcon />测试选中模型 {selected.size ? `(${selected.size})` : ""}</button></div>
    <div className="toolbar"><div className="search"><SearchIcon /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索模型 ID、名称或服务商" /></div><select value={providerFilter} onChange={(e) => setProviderFilter(e.target.value)}><option value="all">全部服务商</option>{snapshot.providers.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><span className="result-count">{filtered.length} 个模型</span></div>
    {notice && <div className="notice error"><AlertIcon />{notice}</div>}
    <div className="table-shell model-table"><table><thead><tr><th className="check-cell"><input type="checkbox" checked={allSelected} onChange={() => setSelected(allSelected ? new Set() : new Set(filtered.map(keyOf)))} aria-label="全选模型" /></th><th>模型</th><th>服务商</th><th>接口</th><th>状态</th><th>延迟</th><th>最后检测</th><th></th></tr></thead><tbody>{filtered.map((model) => { const key = keyOf(model); const active = testing.has(key); return <tr key={key}><td className="check-cell"><input type="checkbox" checked={selected.has(key)} onChange={() => setSelected((old) => { const next = new Set(old); next.has(key) ? next.delete(key) : next.add(key); return next; })} /></td><td><strong className="model-id">{model.modelId}</strong><small>{model.name !== model.modelId ? model.name : "模型名称同 ID"}</small></td><td><span className="provider-inline"><i>{model.providerName.slice(0, 1)}</i>{model.providerName}</span></td><td><span className={`api-tag api-${model.api}`}>{apiLabels[model.api]}</span></td><td><span className={`availability ${model.available && model.api !== "unknown" ? "ok" : "bad"}`} title={model.error}>{model.available && model.api !== "unknown" ? "可用" : "需检测"}</span>{model.statusCode != null && <small>HTTP {model.statusCode}</small>}</td><td className="latency">{model.latencyMs != null ? `${model.latencyMs} ms` : "--"}</td><td>{formatTime(model.lastCheckedAt)}</td><td><button className="icon-button" disabled={active} onClick={() => test([model])} title="发送最小请求">{active ? <span className="spinner" /> : <PlayIcon />}</button></td></tr>; })}{filtered.length === 0 && <tr><td colSpan={8}><div className="table-empty"><BoxesIcon />没有符合条件的模型。先到服务商页面执行“检测模型”。</div></td></tr>}</tbody></table></div>
  </section>;
}

function SettingsPage({ info }: { info: StorageInfo | null }) {
  const [exporting, setExporting] = useState(false); const [notice, setNotice] = useState("");
  async function exportModels() { setExporting(true); try { const path = await api.exportPiModels(); setNotice(`已导出到 ${path}`); } catch (e) { setNotice(messageOf(e)); } finally { setExporting(false); } }
  return <section className="page narrow"><div className="page-heading"><div><p className="eyebrow">本地配置</p><h1>设置</h1><p>检查存储方式，并导出其他工具可读取的模型配置。</p></div></div>
    <div className="settings-section"><div className="settings-heading"><h2>数据与安全</h2><p>敏感信息和普通配置分开保存。</p></div><div className="settings-panel"><div className="setting-row"><div className="setting-icon"><ServerIcon /></div><div><strong>数据存储位置</strong><p>服务商信息、模型状态和余额检测记录</p><code>{info?.dataFile ?? "读取中…"}</code></div></div><div className="setting-row"><div className="setting-icon green"><LockIcon /></div><div><strong>API Key 加密方式</strong><p>密钥不写入 JSON，也不会出现在导出文件中。</p><code>{info?.keyStorage ?? "读取中…"}</code></div><span className="secure-badge"><CheckIcon />已保护</span></div></div></div>
    <div className="settings-section"><div className="settings-heading"><h2>导出</h2><p>生成 pi 可使用的 `models.json`。</p></div><div className="export-panel"><div><div className="export-title"><DownloadIcon /><strong>pi models.json</strong></div><p>包含已启用服务商、Base URL、模型 ID 和接口类型。API Key 会导出为环境变量占位符。</p><div className="code-preview"><span>{`{`}</span><span>  <b>"providers"</b>: [</span><span>    {`{ `}<b>"baseUrl"</b>: <i>"…/v1"</i>, <b>"apiKey"</b>: <i>"MODELDECK_KEY_…"</i>{` }`}</span><span>  ]</span><span>{`}`}</span></div></div><button className="button primary" onClick={exportModels} disabled={exporting}><DownloadIcon />{exporting ? "导出中…" : "导出 models.json"}</button></div>{notice && <div className="notice success"><CheckIcon />{notice}</div>}</div>
    <div className="settings-section"><div className="settings-heading"><h2>关于</h2></div><div className="about-line"><div className="brand-mark small"><BoxesIcon /></div><div><strong>ModelDeck</strong><p>本地 LLM 服务商聚合管理工具 · v0.1.0</p></div><span>不代理请求 · 不上传数据</span></div></div>
  </section>;
}

function App() {
  const [page, setPage] = useState<Page>("providers"); const [snapshot, setSnapshot] = useState<Snapshot>(emptySnapshot); const [info, setInfo] = useState<StorageInfo | null>(null); const [loading, setLoading] = useState(true); const [fatal, setFatal] = useState("");
  async function reload() { try { setSnapshot(await api.getSnapshot()); setFatal(""); } catch (e) { setFatal(messageOf(e)); } finally { setLoading(false); } }
  useEffect(() => { void reload(); void api.storageInfo().then(setInfo).catch(() => null); }, []);
  const nav = [{ id: "providers" as const, label: "服务商", icon: <ServerIcon /> }, { id: "profiles" as const, label: "档案", icon: <PlayIcon /> }, { id: "accounts" as const, label: "账户", icon: <WalletIcon /> }, { id: "keys" as const, label: "API Keys", icon: <LockIcon /> }, { id: "usage" as const, label: "统计", icon: <RefreshIcon /> }, { id: "models" as const, label: "模型", icon: <BoxesIcon />, count: snapshot.models.length }, { id: "settings" as const, label: "设置", icon: <SettingsIcon /> }];
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><BoxesIcon /></div><div><strong>ModelDeck</strong><span>LLM Control Center</span></div></div><nav>{nav.map((item) => <button key={item.id} className={page === item.id ? "active" : ""} onClick={() => setPage(item.id)}>{item.icon}<span>{item.label}</span>{item.count != null && <i>{item.count}</i>}</button>)}</nav><div className="sidebar-footer"><span className="pulse" />本地运行<div>密钥由系统钥匙串保护</div></div></aside>
    <main className="content">{loading ? <div className="loading"><span className="spinner" />正在读取本地数据…</div> : fatal ? <div className="fatal"><AlertIcon /><h2>无法读取本地数据</h2><p>{fatal}</p><button className="button primary" onClick={() => void reload()}>重试</button></div> : page === "providers" ? <ProvidersPage snapshot={snapshot} reload={reload} /> : page === "profiles" ? <ProfilesPage providers={snapshot.providers} profiles={snapshot.profiles ?? []} models={snapshot.models ?? []} reload={reload} /> : page === "accounts" ? <AccountsPage providers={snapshot.providers} /> : page === "keys" ? <KeysPage providers={snapshot.providers} /> : page === "usage" ? <UsagePage providers={snapshot.providers} /> : page === "models" ? <ModelsPage snapshot={snapshot} reload={reload} /> : <SettingsPage info={info} />}</main>
  </div>;
}
export default App;
