import { useEffect, useMemo, useState } from "react";
import * as management from "./management";
import { AlertIcon, LockIcon, PencilIcon, PlusIcon, RefreshIcon, ServerIcon, TrashIcon, WalletIcon, XIcon } from "./icons";
import type { AccountSummary, ManagedGroup, ManagedKey, ManagedKeyInput, Provider, UsageSummary } from "./types";
const money = (value?: number) => value == null ? "--" : new Intl.NumberFormat("zh-CN", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value);
const count = (value?: number) => value == null ? "--" : new Intl.NumberFormat("zh-CN", { maximumFractionDigits: 0 }).format(value);
const err = (value: unknown) => value instanceof Error ? value.message : String(value);
const eligible = (providers: Provider[]) => providers.filter((provider) => provider.enabled && provider.type !== "openai-compatible");

export function AccountsPage({ providers }: { providers: Provider[] }) {
  const supported = eligible(providers); const [items, setItems] = useState<AccountSummary[]>([]); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState("");
  async function sync() { setLoading(true); setNotice(""); const results = await Promise.allSettled(supported.map((p) => management.syncAccount(p.id))); setItems(results.flatMap((result) => result.status === "fulfilled" ? [result.value] : [])); const failures = results.filter((r) => r.status === "rejected") as PromiseRejectedResult[]; if (failures.length) setNotice(failures.map((f) => err(f.reason)).join("；")); setLoading(false); }
  useEffect(() => { void sync(); }, [providers.length]);
  return <section className="page"><div className="page-heading"><div><p className="eyebrow">统一账户</p><h1>账户</h1><p>集中查看余额、消费、订阅与分组状态。</p></div><button className="button primary" onClick={sync} disabled={loading}><RefreshIcon />{loading ? "同步中…" : "同步全部"}</button></div>{notice && <div className="notice error"><AlertIcon />{notice}</div>}
    <div className="account-grid">{items.map((item) => <article className="account-card" key={item.providerId}><header><div className="provider-mark">{item.providerName.slice(0,1)}</div><div><strong>{item.providerName}</strong><span>{item.accountName ?? "账户已连接"}</span></div><i>{item.providerType === "new-api" ? "New API" : "Sub2API"}</i></header><div className="account-balance"><span>可用余额</span><strong>$ {money(item.balance)}</strong>{item.frozenBalance != null && <small>冻结 $ {money(item.frozenBalance)}</small>}</div><div className="account-metrics"><div><span>累计消费</span><b>$ {money(item.used)}</b></div><div><span>请求次数</span><b>{count(item.requestCount)}</b></div><div><span>当前分组</span><b>{item.group ?? "--"}</b></div><div><span>倍率</span><b>{item.multiplier != null ? `${item.multiplier}×` : "--"}</b></div></div><footer><span>{item.subscriptionName ? `${item.subscriptionName} · ${item.subscriptionStatus ?? "active"}` : "按量账户"}</span><span>{item.expiresAt ? `到期 ${new Date(item.expiresAt).toLocaleDateString()}` : "无已知到期时间"}</span></footer></article>)}{!items.length && !loading && <div className="empty span-all"><div className="empty-icon"><WalletIcon /></div><h2>没有可同步的账户</h2><p>请先为 New API 或 Sub2API 配置账户访问令牌。</p></div>}</div>
  </section>;
}

function KeyModal({ providers, groups, current, onClose, onSaved }: { providers: Provider[]; groups: ManagedGroup[]; current?: ManagedKey; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState<ManagedKeyInput>({ providerId: current?.providerId ?? providers[0]?.id ?? "", id: current?.id, name: current?.name ?? "", enabled: current?.enabled ?? true, groupId: current?.groupId ?? "", quota: current?.quota, unlimited: current?.unlimited ?? true, expiresAt: current?.expiresAt }); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const availableGroups = groups.filter((g) => g.providerId === form.providerId);
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { await management.saveManagedKey(form); onSaved(); } catch (e) { setError(err(e)); } finally { setSaving(false); } }
  return <div className="modal-backdrop"><form className="modal key-modal" onSubmit={submit}><header className="modal-header"><div><h2>{current ? "编辑 API Key" : "创建 API Key"}</h2><p>密钥值由服务商生成，列表仅显示掩码。</p></div><button type="button" className="icon-button" onClick={onClose}><XIcon /></button></header><div className="form-grid"><label><span>服务商</span><select disabled={!!current} value={form.providerId} onChange={(e) => setForm({ ...form, providerId: e.target.value, groupId: "" })}>{providers.map((p) => <option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label><span>名称</span><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="例如：MacBook" /></label><label><span>分组</span><select value={form.groupId ?? ""} onChange={(e) => setForm({ ...form, groupId: e.target.value || undefined })}><option value="">自动/默认</option>{availableGroups.map((g) => <option key={g.id} value={g.id}>{g.name}{g.multiplier != null ? ` · ${g.multiplier}×` : ""}</option>)}</select></label><label><span>额度（USD）</span><input type="number" min="0" step="0.01" disabled={form.unlimited} value={form.quota ?? ""} onChange={(e) => setForm({ ...form, quota: Number(e.target.value) })} placeholder="无限额" /></label><label className="span-2"><span>过期时间</span><input type="datetime-local" value={form.expiresAt?.slice(0,16) ?? ""} onChange={(e) => setForm({ ...form, expiresAt: e.target.value ? new Date(e.target.value).toISOString() : undefined })} /></label></div>{error && <div className="inline-error"><AlertIcon />{error}</div>}<footer className="modal-footer"><label className="switch-label"><button type="button" role="switch" className={`switch ${form.unlimited ? "on" : ""}`} onClick={() => setForm({ ...form, unlimited: !form.unlimited })}><span /></button>无限额度</label><div><button type="button" className="button secondary" onClick={onClose}>取消</button><button className="button primary" disabled={saving}>{saving ? "保存中…" : "保存"}</button></div></footer></form></div>;
}

export function KeysPage({ providers }: { providers: Provider[] }) {
  const supported = eligible(providers); const [providerId, setProviderId] = useState(supported[0]?.id ?? ""); const [keys, setKeys] = useState<ManagedKey[]>([]); const [groups, setGroups] = useState<ManagedGroup[]>([]); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState(""); const [editing, setEditing] = useState<ManagedKey | "new" | null>(null);
  async function load() { if (!providerId) return; setLoading(true); setNotice(""); try { const [nextKeys, nextGroups] = await Promise.all([management.listManagedKeys(providerId), management.listGroups(providerId)]); setKeys(nextKeys); setGroups((old) => [...old.filter((g) => g.providerId !== providerId), ...nextGroups]); } catch (e) { setNotice(err(e)); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [providerId]);
  async function toggle(key: ManagedKey) { try { await management.toggleManagedKey(key.providerId, key.id, !key.enabled); await load(); } catch (e) { setNotice(err(e)); } }
  async function remove(key: ManagedKey) { if (!confirm(`永久删除 API Key“${key.name}”？依赖它的客户端会立即失效。`)) return; try { await management.deleteManagedKey(key.providerId, key.id); await load(); } catch (e) { setNotice(err(e)); } }
  return <section className="page"><div className="page-heading"><div><p className="eyebrow">访问凭证</p><h1>API Keys</h1><p>创建、停用、限额并为密钥切换分组。</p></div><button className="button primary" disabled={!supported.length} onClick={() => setEditing("new")}><PlusIcon />创建 API Key</button></div><div className="toolbar"><select value={providerId} onChange={(e) => setProviderId(e.target.value)}>{supported.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="button secondary" onClick={load} disabled={loading}><RefreshIcon />{loading ? "刷新中…" : "刷新"}</button><span className="result-count">{keys.length} 个 Key</span></div>{notice && <div className="notice error"><AlertIcon />{notice}</div>}<div className="table-shell key-table"><table><thead><tr><th>名称 / Key</th><th>状态</th><th>分组</th><th>额度</th><th>已用</th><th>过期时间</th><th>操作</th></tr></thead><tbody>{keys.map((key) => <tr key={`${key.providerId}-${key.id}`}><td><strong className="model-id">{key.name}</strong><small>{key.maskedKey}</small></td><td><button className={`key-status ${key.enabled ? "active" : "inactive"}`} onClick={() => toggle(key)}><span />{key.enabled ? "已启用" : "已停用"}</button></td><td>{key.groupName ?? key.groupId ?? "自动"}</td><td>{key.unlimited ? "无限" : `$ ${money(key.quota)}`}</td><td>{key.used != null ? `$ ${money(key.used)}` : "--"}</td><td>{key.expiresAt ? new Date(key.expiresAt).toLocaleDateString() : "永不过期"}</td><td><div className="row-actions"><button className="icon-button" onClick={() => setEditing(key)} title="编辑"><PencilIcon /></button><button className="icon-button danger" onClick={() => remove(key)} title="删除"><TrashIcon /></button></div></td></tr>)}{!keys.length && !loading && <tr><td colSpan={7}><div className="table-empty"><LockIcon />该服务商还没有 API Key。</div></td></tr>}</tbody></table></div>{editing && <KeyModal providers={supported} groups={groups} current={editing === "new" ? undefined : editing} onClose={() => setEditing(null)} onSaved={async () => { setEditing(null); await load(); }} />}</section>;
}

export function UsagePage({ providers }: { providers: Provider[] }) {
  const supported = eligible(providers); const [items, setItems] = useState<UsageSummary[]>([]); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState("");
  async function load() { setLoading(true); setNotice(""); const results = await Promise.allSettled(supported.map((p) => management.loadUsage(p.id))); setItems(results.flatMap((r) => r.status === "fulfilled" ? [r.value] : [])); const failures = results.filter((r) => r.status === "rejected") as PromiseRejectedResult[]; if (failures.length) setNotice(failures.map((f) => err(f.reason)).join("；")); setLoading(false); }
  useEffect(() => { void load(); }, [providers.length]); const totals = useMemo(() => items.reduce((all, item) => ({ requests: all.requests + item.totalRequests, tokens: all.tokens + (item.totalTokens ?? 0), cost: all.cost + (item.totalCost ?? 0), today: all.today + (item.todayRequests ?? 0) }), { requests: 0, tokens: 0, cost: 0, today: 0 }), [items]);
  return <section className="page"><div className="page-heading"><div><p className="eyebrow">消费洞察</p><h1>使用统计</h1><p>按服务商汇总请求、Token 和实际消费。</p></div><button className="button primary" onClick={load} disabled={loading}><RefreshIcon />{loading ? "同步中…" : "刷新统计"}</button></div>{notice && <div className="notice error"><AlertIcon />{notice}</div>}<div className="stats-strip usage-stats"><div><span>累计请求</span><strong>{count(totals.requests)}</strong></div><div><span>累计 Token</span><strong>{count(totals.tokens)}</strong></div><div><span>累计消费</span><strong>$ {money(totals.cost)}</strong></div><div><span>今日请求</span><strong>{count(totals.today)}</strong></div></div><div className="usage-list">{items.map((item) => <article key={item.providerId}><div className="provider-mark">{item.providerName.slice(0,1)}</div><div><strong>{item.providerName}</strong><span>同步于 {new Date(item.checkedAt).toLocaleTimeString()}</span></div><div><span>请求</span><b>{count(item.totalRequests)}</b></div><div><span>Token</span><b>{count(item.totalTokens)}</b></div><div><span>消费</span><b>$ {money(item.totalCost)}</b></div><div><span>今日</span><b>{count(item.todayRequests)} 次 · $ {money(item.todayCost)}</b></div></article>)}{!items.length && !loading && <div className="empty"><div className="empty-icon"><ServerIcon /></div><h2>暂无统计数据</h2><p>同步支持账户管理的服务商后显示。</p></div>}</div></section>;
}
