import { useState } from "react";
import * as profilesApi from "./profiles";
import { AlertIcon, CheckIcon, LockIcon, PencilIcon, PlayIcon, PlusIcon, ServerIcon, TrashIcon, XIcon } from "./icons";
import type { LaunchPreview, ModelStatus, Provider, ToolProfile, ToolProfileInput } from "./types";
const message = (value: unknown) => value instanceof Error ? value.message : String(value);

function ProfileModal({ providers, models, current, onClose, onSaved }: { providers: Provider[]; models: ModelStatus[]; current?: ToolProfile; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState<ToolProfileInput>({ id: current?.id, name: current?.name ?? "", tool: current?.tool ?? "codex", providerId: current?.providerId ?? providers[0]?.id ?? "", model: current?.model ?? "", executable: current?.executable ?? "" }); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const providerModels = models.filter((model) => model.providerId === form.providerId);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await profilesApi.saveProfile(form); onSaved(); } catch (e) { setError(message(e)); } finally { setBusy(false); } }
  return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><header className="modal-header"><div><h2>{current ? "编辑配置档案" : "新建配置档案"}</h2><p>档案引用 ModelDeck 服务商，不复制外部工具登录态。</p></div><button type="button" className="icon-button" onClick={onClose}><XIcon /></button></header><div className="form-grid"><label><span>档案名称</span><input required value={form.name} onChange={(e) => setForm({...form,name:e.target.value})} placeholder="例如：工作 Codex" /></label><label><span>工具</span><select value={form.tool} onChange={(e) => setForm({...form,tool:e.target.value as "codex"|"claude"})}><option value="codex">Codex CLI</option><option value="claude">Claude Code</option></select></label><label><span>服务商</span><select required value={form.providerId} onChange={(e) => setForm({...form,providerId:e.target.value})}>{providers.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label><span>模型（可选）</span><select value={form.model} onChange={(e)=>setForm({...form,model:e.target.value})}><option value="">工具默认模型</option>{providerModels.map((model)=><option key={model.modelId} value={model.modelId}>{model.modelId}</option>)}</select><small>{providerModels.length ? `已加载 ${providerModels.length} 个模型` : "该服务商尚未检测模型"}</small></label><label className="span-2"><span>可执行文件（可选）</span><input value={form.executable} onChange={(e)=>setForm({...form,executable:e.target.value})} placeholder={form.tool === "codex" ? "/path/to/codex" : "/path/to/claude"}/><small>留空时从 PATH 查找。本机当前未检测到命令时请填写完整路径。</small></label></div>{error&&<div className="inline-error"><AlertIcon />{error}</div>}<footer className="modal-footer"><span /><div><button type="button" className="button secondary" onClick={onClose}>取消</button><button className="button primary" disabled={busy}>{busy?"保存中…":"保存档案"}</button></div></footer></form></div>;
}

function PreviewModal({ preview, onClose, onLaunch, busy }: { preview: LaunchPreview; onClose:()=>void; onLaunch:()=>void; busy:boolean }) { return <div className="modal-backdrop"><div className="modal preview-modal"><header className="modal-header"><div><h2>隔离启动预览</h2><p>只启动新的终端子进程，不修改原工具配置。</p></div><button className="icon-button" onClick={onClose}><XIcon /></button></header><div className="preview-body"><div className="isolation-banner"><LockIcon /><div><strong>原配置保持不变</strong><span>{preview.untouchedPaths.join(" · ")}</span></div></div><section><h3>将启动</h3><code>{preview.executable}</code>{preview.isolatedHome&&<><h3>独立配置目录</h3><code>{preview.isolatedHome}</code></>}</section><section><h3>仅对子进程注入</h3>{preview.environment.map((item)=><div className="env-row" key={item}><CheckIcon />{item}</div>)}</section><section><h3>命令预览</h3><code>{preview.commandPreview}</code></section></div><footer className="modal-footer"><span /><div><button className="button secondary" onClick={onClose}>取消</button><button className="button primary" onClick={onLaunch} disabled={busy}><PlayIcon />{busy?"启动中…":"在新终端启动"}</button></div></footer></div></div>; }

export function ProfilesPage({ providers, profiles, models, reload }: { providers: Provider[]; profiles: ToolProfile[]; models: ModelStatus[]; reload:()=>Promise<void> }) {
 const usable=providers.filter((p)=>p.enabled&&p.hasApiKey); const [editing,setEditing]=useState<ToolProfile|"new"|null>(null); const [preview,setPreview]=useState<LaunchPreview|null>(null); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState("");
 async function inspect(profile:ToolProfile){setNotice("");try{setPreview(await profilesApi.previewLaunch(profile.id));}catch(e){setNotice(message(e));}}
 async function launch(){if(!preview)return;setBusy(true);try{await profilesApi.launchProfile(preview.profileId);setPreview(null);await reload();}catch(e){setNotice(message(e));}finally{setBusy(false);}}
 async function remove(profile:ToolProfile){if(!confirm(`删除配置档案“${profile.name}”？不会删除任何 Codex/Claude 原配置。`))return;try{await profilesApi.deleteProfile(profile.id);await reload();}catch(e){setNotice(message(e));}}
 return <section className="page"><div className="page-heading"><div><p className="eyebrow">隔离运行</p><h1>配置档案</h1><p>切换服务商账号，并在独立环境中启动 Codex 或 Claude Code。</p></div><button className="button primary" disabled={!usable.length} onClick={()=>setEditing("new")}><PlusIcon />新建档案</button></div><div className="isolation-summary"><LockIcon /><div><strong>默认零污染模式</strong><span>不读取、不覆盖 ~/.codex、~/.claude 或 shell 配置。Codex 使用独立 CODEX_HOME；Claude 仅使用子进程环境变量。</span></div></div>{notice&&<div className="notice error"><AlertIcon />{notice}</div>}<div className="profile-grid">{profiles.map((profile)=>{const provider=providers.find((p)=>p.id===profile.providerId);return <article className={`profile-card ${profile.active?"active":""}`} key={profile.id}><header><div className="tool-mark">{profile.tool==="codex"?"CX":"CC"}</div><div><strong>{profile.name}</strong><span>{profile.tool==="codex"?"Codex CLI":"Claude Code"}</span></div>{profile.active&&<i>当前</i>}</header><dl><div><dt>服务商</dt><dd>{provider?.name??"已删除"}</dd></div><div><dt>模型</dt><dd>{profile.model||"工具默认"}</dd></div><div><dt>隔离方式</dt><dd>{profile.tool==="codex"?"独立 CODEX_HOME":"子进程环境变量"}</dd></div></dl><footer><button className="button primary" onClick={()=>inspect(profile)}><PlayIcon />预览并启动</button><button className="icon-button bordered" onClick={()=>setEditing(profile)}><PencilIcon /></button><button className="icon-button bordered danger" onClick={()=>remove(profile)}><TrashIcon /></button></footer></article>})}{!profiles.length&&<div className="empty span-all"><div className="empty-icon"><ServerIcon /></div><h2>还没有配置档案</h2><p>创建档案后即可隔离启动 Codex 或 Claude Code。</p></div>}</div>{editing&&<ProfileModal providers={usable} models={models} current={editing==="new"?undefined:editing} onClose={()=>setEditing(null)} onSaved={async()=>{setEditing(null);await reload();}}/>}{preview&&<PreviewModal preview={preview} busy={busy} onClose={()=>setPreview(null)} onLaunch={launch}/>}</section>;
}
